"""empty message

Revision ID: 359510429fbb
Revises: de06b4c60202
Create Date: 2023-08-16 11:58:03.184052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359510429fbb'
down_revision = 'de06b4c60202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
