"""empty message

Revision ID: 94c1dd01e27c
Revises: 565bc38067dd
Create Date: 2023-08-17 16:29:06.353460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c1dd01e27c'
down_revision = '565bc38067dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('element_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('element_type', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('favorites_planets_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_characters_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_users_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('users_id')
        batch_op.drop_column('characters_id')
        batch_op.drop_column('planets_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('characters_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_users_id_fkey', 'users', ['users_id'], ['id'])
        batch_op.create_foreign_key('favorites_characters_id_fkey', 'characters', ['characters_id'], ['id'])
        batch_op.create_foreign_key('favorites_planets_id_fkey', 'planets', ['planets_id'], ['id'])
        batch_op.drop_column('element_type')
        batch_op.drop_column('element_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
