"""empty message

Revision ID: 986cdb9df99b
Revises: 20e8d0161713
Create Date: 2023-08-12 09:50:45.444558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986cdb9df99b'
down_revision = '20e8d0161713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
